server:
  port: 8888

spring:
  datasource:
    username: root
    password: pl010425  #改成自己数据库到密码
    url: jdbc:mysql://localhost:3306/huoguo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.huoguo.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false
  params: count=countSql
